### ISSUE TITLE
UC浏览器不行

### ISSUE THREAD

**Issue by luoguibin** [any86/be-full#1]

**Comment by any86** [comment]
是安卓还是ios版本的uc?
是直接看首页的demo没生效吗? 请问是用打包工具用的? 还是直接在浏览器中引入script用的?

**Comment by luoguibin** [comment]
> 是安卓还是ios版本的uc?
> 是直接看首页的demo没生效吗? 请问是用打包工具用的? 还是直接在浏览器中引入script用的?

安卓uc，直接查看demo

**Comment by any86** [comment]
我猜到了可能是看的demo, 我demo是在浏览器里用的es6的模块引入方式, uc应该是不支持, 实际项目用npm引入打包后是没问题的.

**Comment by any86** [comment]
稍后我重新做个demo

**Comment by luoguibin** [comment]
额，你更新demo了吗？还是不起作用

**Comment by any86** [comment]
@luoguibin 重制了demo, 经过测试UC下无问题
https://any86.github.io/be-full/example/
