### ISSUE TITLE
API有没有开启和退出全屏的事件回调

### ISSUE THREAD

**Issue by Leopold1988** [any86/be-full#14]
我想在**开启全屏**和**退出全屏**事件回调里做些事情，可是没有想到相关的API。于是我自己去监测ESC的keyup，ESC的确触发了退出全屏但是我没有捕获到，请问这种情况改如何处理。

**Comment by any86** [comment]
可以, beFull返回的是一个promise, 当然这个是浏览器api返回的, 也就是`requestFullScreen`这个方法返回的, 所以你可以[参考这里](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/requestFullScreen)

简单来说就是可以:
```javascript
beFull().then(()=>{
    // 已经全屏了
})
```

**Comment by Leopold1988** [comment]
原来是这样，没有注意返回的使promise，希望可以丰富下文档~

**Comment by any86** [comment]
> 原来是这样，没有注意返回的使promise，希望可以丰富下文档~

好的
